# -*- coding: utf-8 -*-
{
    'name': 'Service Teams',
    'version': '16.0.1',
    'author': 'Eisa Ahmed',
    'category': 'Service',
    'summary': 'Field Service',
    'description': """
        This application has various custom forms and functionalities integrated in it and with other odoo's built in modules. 
 """,
    'website': 'https://www.fiverr.com/eisaahmed63',
    'depends': ['base', 'hr', 'mail', 'calendar', 'account', 'fleet', 'base_geolocalize', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        # 'data/channel.xml',
        # 'data/scheduled_action.xml',
        # 'data/mail_template_data.xml',
        # 'wizard/confirm_view.xml',
        # 'views/calendar_job_view.xml',
        # 3'views/service_team_views.xml',
        # 'views/account_payment_view.xml',
        # 'views/account_view.xml',
        # 'views/purchase_view.xml',
        # '4views/service_team_collection_views.xml',
        # 5'views/partner_view.xml',
        # 'views/scheduling.xml',
        'quotation/view_quotation.xml',
        # 'quotation/report/quotation_print_template.xml',
        # 'quotation/report/quotation_print.xml',
        'contract/view_contract.xml',
        # 'contract/report/contract_print_draft.xml',
        # 'contract/report/contract_template.xml',
        # 'contract/report/contract_print.xml',
        # 'report/job_print_template.xml',
        # 'report/job_print.xml',
        # '3views/menu.xml',
        'hr/employee_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
