# -*- coding: utf-8 -*-
{
    'name': 'Service Teams',
    'version': '16.0.1',
    'author': 'Eisa Ahmed',
    'category': 'Service',
    'summary': 'Field Service',
    'description': """
        This application has various custom forms and functionalities integrated in it and with other odoo's built in modules. 
 """,
    'website': 'https://www.fiverr.com/eisaahmed63',
    'depends': ['base', 'hr', 'mail', 'calendar', 'account', 'fleet', 'base_geolocalize', 'purchase', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/client.obligation.csv',
        'data/contract.obligation.csv',
        'data/covered.pest.csv',
        'data/job.area.csv',
        'data/job.type.csv',
        'data/service.callback.csv',
        'data/service.frequency.csv',
        'data/service.payment.term.csv',
        'data/service.scope.work.csv',
        'data/service.validity.csv',
        'data/area.area.csv',
        'data/premise.type.csv',
        'data/data.xml',
        'data/scheduled_action.xml',
        'data/mail_template_data.xml',
        'views/calendar_job_view.xml',
        'views/service_team_views.xml',
        'views/account_view.xml',
        'views/purchase_view.xml',
        'views/service_team_collection_views.xml',
        'views/partner_view.xml',
        'views/scheduling.xml',
        'quotation/view_quotation.xml',
        'report/quotation_print_template.xml',
        'report/quotation_print.xml',
        'contract/view_contract.xml',
        'report/contract_print_draft.xml',
        'report/contract_template.xml',
        'report/contract_print.xml',
        'report/job_print_template.xml',
        'report/job_print.xml',
        'views/menu.xml',
        'hr/employee_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
